### ISSUE TITLE
VS equivalent of VS Code Command Palette

### ISSUE THREAD

**Issue by gep13** [gep13/cake-vs#2]
Within the VS Code extension for VS Code we have a couple of commands:

![image](https://cloud.githubusercontent.com/assets/1271146/15276166/04edf038-1ad8-11e6-80c7-41e7c78a3a51.png)

One of which expands in several further options for the user to select:

![image](https://cloud.githubusercontent.com/assets/1271146/15276168/1cf90708-1ad8-11e6-9fb1-937091060be8.png)

It would be good for the Visual Studio extension for Cake to have something similar.

**Comment by gep13** [comment]
@hmemcpy what would be your suggestion on the right approach for an equivalent for this functionality in Visual Studio?  Thanks!

**Comment by hmemcpy** [comment]
Well, unfortunately there isn't much "freedom" in VS extensions, my initial hunch - those would have to be VS Commands (accessible via the menu/toolbar or the quick find thing). Each expansion can be an inline popup or a tool window that opens...

**Comment by gep13** [comment]
@hmemcpy yes, that was my initial thinking as well, I was just curious is there was another way as well.  I think a Menu/Toolbar is a sensible place to put the options though, just wanted to make sure that I wasn't missing something obvious.  Cheers!

**Comment by gep13** [comment]
Replaced with https://github.com/agc93/Cake.VisualStudio
