### ISSUE TITLE
Cake Icon in Solution Explorer

### ISSUE THREAD

**Issue by gep13** [gep13/cake-vs#3]
Within the IgnoreFiles VS Extension from @madskristensen I "think" I am right in saying that he is associating a, icon with the different ignore files, so that these icons appear in the solution explorer:

https://github.com/madskristensen/IgnoreFiles/blob/master/src/ContentType/icons.pkgdef

I wonder whether something like this would be possible for the build.cake file?  Can we associated the cake icon with the build.cake file, so that it appears in the solution explorer?

**Comment by gep13** [comment]
@hmemcpy do you know if this is possible?

**Comment by hmemcpy** [comment]
The `KnownMonikers`, as the name suggests, are icons that are known to Visual Studio (you can see a list of them here: http://glyphlist.azurewebsites.net/knownmonikers/)
I'm fairly certain it's possible to register a custom icon and give it a name, so it can be assigned. But I haven't done this, so I don't know for sure.
Another option is to assign .cake files to an icon in Windows, and it be picked up in Visual Studio too.

I need to look into it some more (perhaps the folks in [extendvs](https://gitter.im/Microsoft/extendvs) have better ideas...

**Comment by gep13** [comment]
>@hmemcpy said...
I need to look into it some more (perhaps the folks in extendvs have better ideas..

Perfect, I will reach out to them, thanks, didn't know about that gitter room :+1:

**Comment by hmemcpy** [comment]
Oh yeah, that room is a goldmine for anything extension related. All the cool kids hang out there :)

**Comment by hmemcpy** [comment]
Also, I completely forgot that I've done something like this before in code: using some goodies from the VS Project System (aka CPS, Common Project System)!
Totally doable: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/scenario/provide_custom_icons_for_the_project_or_item_type.md

**Comment by gep13** [comment]
Aw sweet! I will take a look at this as well. Cheers!

**Comment by gep13** [comment]
@hmemcpy ok, I am reading through that article, but I am clearly missing something.  Do you know if there is an example somewhere that makes use of it?

**Comment by hmemcpy** [comment]
Oof, I think I misled you about CPS - this would only work for CPS-based projects, and unfortunately, the existing C# project system is not based on CPS (yet, they are rewriting it for VS"15")
I'll have another look over the weekend...

**Comment by gep13** [comment]
@hmemcpy ah, ok. Not a problem.

**Comment by gep13** [comment]
Replaced with: https://github.com/agc93/Cake.VisualStudio
