### ISSUE TITLE
Add option to directly debug .cake files

### ISSUE THREAD

**Issue by gep13** [gep13/cake-vs#4]
This would be similar to what @hmemcpy has done over here:

https://github.com/hmemcpy/AnyScriptCs

**Comment by hmemcpy** [comment]
Please note that the link above is utilizing new functionality in VS "15" (aka vNext), that supports the "File -> Open Folder" featire, which lets you edit and debug individual files.
This requires a bit more work to do properly in older versions (when opening individual files), however it might be completely possible by having a custom workspace, as planned in #1

**Comment by gep13** [comment]
@hmemcpy just so I am clear, why is this approach only possible in Visual Studio 15?  And why the requirement for the Open Folder?  Typically a build.cake file is contained within the same folder structure as an existing Visual Studio solution.  Is it possible to add the build.cake file as a solution item, and then set it as the start up file for the project in the same way?

**NOTE:** I haven't started looking at the AnyScriptCS extension yet, so this is probably a naive question, but I just wanted to put an issue/question up while I remember about it.

**Comment by gep13** [comment]
@hmemcpy looks like you answered my question, without me even asking it.

Ok, that makes sense.  I am ok with targetting VS 15, assuming that I can have some parts of the extension work in one version, and other parts only work in the new ones, as we discussed previously. 

I do like the idea of adding it into the custom workspace functionality as well though.  Definitely things to look at here.

**Comment by hmemcpy** [comment]
I believe we can easily support both cases. 
Scriptcs worked around this by introducing a custom command that would wrap a .csx file in a temp solution/project, and open it in VS (see https://github.com/scriptcs/scriptcs/pull/1109)
Not quite sure this is needed in VS2015+ to be honest, but I need to take a closer look.

**Comment by gep13** [comment]
Replaced with: https://github.com/agc93/Cake.VisualStudio
